s = set()
n = int(input("numm1 : "))
s.add(n)
n = int(input("numm1 : "))
s.add(n)
n = int(input("numm1 : "))
s.add(n)
n = int(input("numm1 : "))
s.add(n)
n = int(input("numm1 : "))
s.add(n)
n = int(input("numm1 : "))
s.add(n)
n = int(input("numm1 : "))
s.add(n)
n = int(input("numm1 : "))
s.add(n)
print(s)